FROM node:18-alpine

WORKDIR /app

COPY frontend/package*.json ./frontend/
COPY shared/package.json ./shared/package.json
COPY shared/dist ./shared/dist

WORKDIR /app/frontend
RUN npm install

COPY frontend ./

EXPOSE 3000

CMD ["npm", "start"]
