FROM node:18-alpine

WORKDIR /app

COPY backend/package*.json ./backend/
COPY shared/package.json ./shared/package.json
COPY shared/dist ./shared/dist

WORKDIR /app/backend
RUN npm install

COPY backend ./

EXPOSE 8080

CMD ["npm", "run", "dev"]
