import { Ticker } from '../domain/models/Ticker';

export const DEFAULT_TICKERS: readonly Ticker[] = [
  {
    symbol: 'EUR/USD',
    name: 'Euro / US Dollar',
    basePrice: 1.085,
    type: 'Forex',
    isFavorite: true,
    inPortfolio: true,
    icon: 'https://flagcdn.com/w40/eu.png|https://flagcdn.com/w40/us.png',
  },
  {
    symbol: 'GBP/JPY',
    name: 'British Pound / Yen',
    basePrice: 190.2,
    type: 'Forex',
    isFavorite: false,
    inPortfolio: false,
    icon: 'https://flagcdn.com/w40/gb.png|https://flagcdn.com/w40/jp.png',
  },
  {
    symbol: 'USD/JPY',
    name: 'US Dollar / Yen',
    basePrice: 151.4,
    type: 'Forex',
    isFavorite: true,
    inPortfolio: false,
    icon: 'https://flagcdn.com/w40/us.png|https://flagcdn.com/w40/jp.png',
  },
  {
    symbol: 'XAU/USD',
    name: 'Gold',
    basePrice: 2350.5,
    type: 'Metals',
    isFavorite: true,
    inPortfolio: true,
    icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/paxg.png|https://flagcdn.com/w40/us.png',
  },
  {
    symbol: 'XAG/USD',
    name: 'Silver',
    basePrice: 28.3,
    type: 'Metals',
    isFavorite: false,
    inPortfolio: false,
    icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/ltc.png|https://flagcdn.com/w40/us.png',
  },
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    basePrice: 175.5,
    type: 'Shares',
    isFavorite: true,
    inPortfolio: false,
    icon: 'https://www.google.com/s2/favicons?domain=apple.com&sz=128',
  },
  {
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    basePrice: 205.2,
    type: 'Shares',
    isFavorite: false,
    inPortfolio: true,
    icon: 'https://www.google.com/s2/favicons?domain=tesla.com&sz=128',
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corp.',
    basePrice: 900.5,
    type: 'Shares',
    isFavorite: true,
    inPortfolio: true,
    icon: 'https://www.google.com/s2/favicons?domain=nvidia.com&sz=128',
  },
  {
    symbol: 'BTC-USD',
    name: 'Bitcoin',
    basePrice: 64200.0,
    type: 'Crypto',
    isFavorite: true,
    inPortfolio: true,
    icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/btc.png|https://flagcdn.com/w40/us.png',
  },
  {
    symbol: 'ETH-USD',
    name: 'Ethereum',
    basePrice: 3100.0,
    type: 'Crypto',
    isFavorite: false,
    inPortfolio: false,
    icon: 'https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/eth.png|https://flagcdn.com/w40/us.png',
  },
  {
    symbol: 'US30',
    name: 'Wall Street 30',
    basePrice: 39000.0,
    type: 'Indices',
    isFavorite: false,
    inPortfolio: false,
    icon: 'https://www.google.com/s2/favicons?domain=wsj.com&sz=128',
  },
  {
    symbol: 'SPX500',
    name: 'S&P 500',
    basePrice: 5100.0,
    type: 'Indices',
    isFavorite: true,
    inPortfolio: false,
    icon: 'https://www.google.com/s2/favicons?domain=spglobal.com&sz=128',
  },
  {
    symbol: 'USOIL',
    name: 'Crude Oil',
    basePrice: 82.5,
    type: 'Commodities',
    isFavorite: false,
    inPortfolio: true,
    icon: 'https://www.google.com/s2/favicons?domain=oilprice.com&sz=128',
  },
];
